Filter quantum numbers
ComPWA/qrules pull request #287
Opened 2024-10-04 12:51 UTC by grayson-helmholz

As `CSPSolver.find_solutions()` just takes a general `QNProblemSet` it should be possible 
to  reduce the set of constraints (i.e. conservation rules) the solver takes into account for 
finding the solutions of a decay. 
A possible way to implement this is to use the `StateTransitionManager` to generate the 
full set of rules for a certain decay and just filter it to contain only the desired 
constraints before passing it to `CSPSolver`.

2024-10-04 14:09 UTC, redeboer requested changes
Ported remaining review comments from https://github.com/ComPWA/qrules/pull/278

2024-10-21 10:05 UTC, redeboer requested changes
Nice that it's working 🙌 

(After offline discussion):
Let's expose this `filter_quantum_number_problem_set()` function and write an example with visualization in the "Conservation rules" notebook. If that turns out to look concise, illustrative, and useable enough, we can keep this new function in the API.

2024-10-29 14:12 UTC, grayson-helmholz commented on tests/unit/test_solving.py
> +            # EdgeQuantumNumbers.spin_projection,  # can be left out to reduce the number of solutions
implemented

2024-10-30 09:26 UTC, redeboer commented on docs/usage/conservation.ipynb
>     "metadata": {
Could you undo the changes to the notebooks that you did not intend to edit in this PR?

2024-10-30 10:00 UTC, redeboer requested changes
Good job! The new section in the documentation is particularly good 👌 
Some final smaller changes are suggested below.

2024-11-04 13:34 UTC, grayson-helmholz commented on tests/unit/test_solving.py
> +    return qn_problem_sets[0]
Yes, should have had this built-in in mind.

2024-11-04 13:54 UTC, grayson-helmholz commented on src/qrules/solving.py
> +    node_properties_and_domains: Iterable[NodeQuantumNumberTypes],
When this function was originally written to test the behaviour in the `merge_rules&priorities`-branch and used `attrs.evolve`, this was supposed to signal during development that it also copied the domains and not only the (fused) rules and priorities.
Will be renamed as it now constructs whole new Settings anyway.

2024-11-04 14:09 UTC, grayson-helmholz commented on docs/usage/visualize.ipynb
> +    "### Filtering Quantum Number Problem Sets\n",
Makes sense, did not think about that.

2024-11-04 15:20 UTC, grayson-helmholz commented on docs/usage/visualize.ipynb
> +    "graphviz.Source(dot)"
Will post an issue about that

2024-11-05 10:20 UTC, grayson-helmholz commented on docs/usage/visualize.ipynb
> +    "graphviz.Source(dot)"
Is now mentioned in #301

2024-11-05 10:30 UTC, redeboer commented on docs/usage/visualize.ipynb
> +    "graphviz.Source(dot)"
It has to do with the quantum number sets from which the `CSPSolver` gets its info, specifically here:
```python
solver = CSPSolver([
    qrules.system_control.create_edge_properties(part)
    for part in qrules.particle.load_pdg()
])
```
So you probably want to filter the required properties from `qrules.system_control.create_edge_properties(part)`.

2024-11-06 08:29 UTC, redeboer approved these changes
Good job! 🥇

2024-11-06 08:30 UTC, merged