MAINT: have `qn_domains`-keys in Node/EdgeSettings be the types of the resp. domain
ComPWA/qrules pull request #292
Opened 2024-10-16 10:23 UTC by grayson-helmholz

In order to have more reliable type-checking the keys of the `qn_domains`-dictionary should be the types of the respective domains themselves. This avoids for example the use of wrong quantum numbers (EdgeQNs for a node, etc.)

Closes #281

2024-10-16 11:24 UTC, grayson-helmholz commented
Hopefully merging of #289 will make it easier to have "CI / doc / nb" pass

2024-10-18 10:35 UTC, redeboer requested changes

2024-10-18 10:35 UTC, redeboer commented on docs/conf.py
> +nitpick_temp_names = [*nitpick_temp_eqdge_names, *nitpick_temp_node_names]
```suggestion
nitpick_temp_names = [
    *attrs.fields_dict(EdgeQuantumNumbers),
    *attrs.fields_dict(NodeQuantumNumbers),
]
```

2024-10-18 13:03 UTC, redeboer requested changes

2024-10-18 13:03 UTC, redeboer commented on docs/conf.py
> +nitpick_temp_names = [*nitpick_temp_edge_names, *nitpick_temp_node_names]
```suggestion
nitpick_temp_names = [
    *pick_newtype_attrs(EdgeQuantumNumbers),
    *pick_newtype_attrs(NodeQuantumNumbers),
]
```

2024-10-18 13:03 UTC, redeboer commented on docs/conf.py
> +
Could you move this one before all the variables (options) in this file? So right after the imports.

2024-10-18 13:10 UTC, redeboer requested changes

2024-10-18 13:10 UTC, redeboer commented on docs/conf.py
> +nitpick_temp_node_names = pick_newtype_attrs(NodeQuantumNumbers)
These are duplicate now
```suggestion
```

2024-10-18 15:03 UTC, merged